"""Week 2 request/response models for the REST API and WebSocket payloads."""
from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from backend.core.enums import (
    AlertType,
    CameraStatus,
    CameraType,
    Direction,
    HardwareStatus,
    RiskLevel,
    UserRole,
    ZoneRegion,
    ZoneType,
)
from backend.schemas.alert import ALERT_ID_PATTERN, AlertResponse
from backend.schemas.camera import CameraBase, CameraResponse
from backend.schemas.common import InputSchema, Latitude, Longitude, ORMSchema, RiskScore
from backend.schemas.event import EventResponse
from backend.schemas.evidence import EvidenceResponse
from backend.schemas.hardware_registry import HardwareResponse


class MessageResponse(BaseModel):
    message: str


# ------------------------------------------------------------------ auth

class LoginUserInfo(ORMSchema):
    user_id: UUID
    username: str
    role: UserRole
    camera_access: List[str] = Field(default_factory=list)
    zone_access: List[str] = Field(default_factory=list)


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: Literal["bearer"] = "bearer"
    expires_in: int
    user: LoginUserInfo


class RefreshRequest(InputSchema):
    refresh_token: str = Field(min_length=20, max_length=4096)


class AccessTokenResponse(BaseModel):
    access_token: str
    token_type: Literal["bearer"] = "bearer"
    expires_in: int


class LogoutRequest(InputSchema):
    refresh_token: Optional[str] = Field(default=None, max_length=4096)


# ------------------------------------------------------------------ cameras

class CameraRegisterRequest(CameraBase):
    """camera_id is generated by the server (CAM-{N|S|E|W}-{NNN}); status comes from the stream probe."""


class CameraRegisterResponse(CameraResponse):
    connection_ok: bool
    preview_frame: Optional[str] = Field(default=None, description="Base64 JPEG captured during registration")
    message: str


class CameraWithAlertCount(CameraResponse):
    active_alert_count: int = 0


class CameraListWithAlertsResponse(BaseModel):
    items: List[CameraWithAlertCount] = Field(default_factory=list)
    total: int


class CameraDetailResponse(CameraResponse):
    active_alert_count: int
    viewer_count: int
    recent_alerts: List[AlertResponse] = Field(default_factory=list)


class CameraStatusUpdate(InputSchema):
    status: CameraStatus


class CameraEditRequest(InputSchema):
    """Editable camera metadata. camera_id, status and the stream URL are managed by their own endpoints.
    Only the fields present in the request are changed; gps_lat/gps_lng may be set to null together."""

    name: Optional[str] = Field(default=None, min_length=1, max_length=100)
    location_name: Optional[str] = Field(default=None, max_length=200)
    gps_lat: Optional[Latitude] = None
    gps_lng: Optional[Longitude] = None
    sector_name: Optional[str] = Field(default=None, max_length=100)
    camera_type: Optional[CameraType] = None
    zone_region: Optional[ZoneRegion] = None

    @model_validator(mode="after")
    def _consistent(self) -> "CameraEditRequest":
        sent = self.model_fields_set
        if not sent:
            raise ValueError("No fields to update")
        if ("gps_lat" in sent) != ("gps_lng" in sent) or (self.gps_lat is None) != (self.gps_lng is None):
            raise ValueError("gps_lat and gps_lng must be provided together")
        for required in ("name", "camera_type", "zone_region"):
            if required in sent and getattr(self, required) is None:
                raise ValueError(f"{required} cannot be null")
        return self


class CalibrationPoint(InputSchema):
    """One landmark seen in both views: where it is in the camera image and where it is on the map."""

    image: List[float] = Field(min_length=2, max_length=2, description="[x, y] in camera pixels")
    geo: List[float] = Field(min_length=2, max_length=2, description="[latitude, longitude]")


class CameraCalibrationRequest(InputSchema):
    """Ground-plane calibration: 4+ landmarks that lie on the ground, spread across the camera's view."""

    points: List[CalibrationPoint] = Field(min_length=4, max_length=24)
    image_size: List[int] = Field(min_length=2, max_length=2, description="[width, height] of the camera frame")

    @field_validator("image_size")
    @classmethod
    def _frame_size(cls, value: List[int]) -> List[int]:
        width, height = int(value[0]), int(value[1])
        if not (2 <= width <= 16384 and 2 <= height <= 16384):
            raise ValueError("image_size must be the camera frame size in pixels")
        return [width, height]


class CameraCalibrationResponse(BaseModel):
    camera_id: str
    points: List[CalibrationPoint]
    image_size: List[int]
    #: Average distance between each landmark and where the fitted plane puts it.
    error_px: float
    calibrated_at: datetime
    #: Map-drawn zones of this camera whose pixel polygon was recomputed by this calibration.
    zones_projected: int = 0


class HostLocationResponse(BaseModel):
    """Position of the console host from the OS location service (fallback when the browser has none)."""

    lat: float
    lng: float
    accuracy_m: Optional[int] = None
    source: Literal["windows-location-service"]
    captured_at: datetime


class CameraStatusResponse(CameraResponse):
    previous_status: CameraStatus
    offline_alert_id: Optional[str] = None


class CameraDeleteResponse(BaseModel):
    camera_id: str
    deletion: Literal["hard", "soft"]
    message: str


class StreamTestResponse(BaseModel):
    camera_id: Optional[str] = None
    connected: bool
    fps: float = 0.0
    resolution: Optional[str] = None
    frame_preview: Optional[str] = None
    latency_ms: int = 0
    message: str


# ------------------------------------------------------------------ alerts

class CameraAlertCount(BaseModel):
    camera_id: str
    count: int


class HourlyCount(BaseModel):
    hour: int = Field(ge=0, le=23)
    count: int


class AlertStatsResponse(BaseModel):
    total_today: int
    critical_today: int
    unacknowledged: int
    by_type: Dict[str, int]
    by_risk_level: Dict[str, int]
    by_camera: List[CameraAlertCount]
    hourly_trend: List[HourlyCount]
    timezone: str


# ------------------------------------------------------------------ events

class TrackHistoryResponse(BaseModel):
    track_id: int
    events: List[EventResponse]
    total_events: int
    total_time_seconds: int
    alert_count: int
    max_risk_score: int
    cameras: List[str]


class TimelinePoint(BaseModel):
    timestamp: datetime
    camera_id: str
    cx: Optional[int] = None
    cy: Optional[int] = None
    zone_name: Optional[str] = None
    zone_type: Optional[str] = None
    risk_score: int = 0
    risk_level: Optional[str] = None
    object_class: Optional[str] = None


class TimelineResponse(BaseModel):
    track_id: int
    source: Literal["tracked_objects", "event_positions"]
    points: List[TimelinePoint]


class EventPage(BaseModel):
    items: List[EventResponse]
    total: int


# ------------------------------------------------------------------ evidence

class EvidenceUploadResponse(BaseModel):
    evidence_id: int
    file_hash: str
    file_name: str
    file_size_bytes: int
    evidence_type: str
    job_id: str
    file_url: str
    message: str


class EvidenceDetailResponse(EvidenceResponse):
    file_url: str
    file_exists: bool


class EvidencePage(BaseModel):
    items: List[EvidenceDetailResponse]
    total: int


class EvidenceVerifyResponse(BaseModel):
    evidence_id: int
    stored_hash: str
    computed_hash: Optional[str]
    integrity: Literal["valid", "tampered", "missing"]
    verified_at: datetime


class EvidenceArchiveResponse(BaseModel):
    evidence_id: int
    is_hot_storage: bool
    archived_at: datetime
    file_path: str
    message: str


# ------------------------------------------------------------------ hardware

class HardwareTypeSummary(BaseModel):
    total: int = 0
    connected: int = 0
    disconnected: int = 0
    error: int = 0
    standby: int = 0
    items: List[HardwareResponse] = Field(default_factory=list)


class HardwareTestResponse(BaseModel):
    hardware_id: int
    connected: bool
    latency_ms: int
    status: HardwareStatus
    message: str


# ------------------------------------------------------------------ stats / health

class StatsResponse(BaseModel):
    persons_detected_today: int
    vehicles_detected_today: int
    active_alerts: int
    critical_alerts: int
    cameras_online: int
    cameras_total: int
    cameras_offline: int
    cameras_degraded: int
    avg_system_fps: float
    cpu_percent: float
    ram_percent: float
    gpu_percent: Optional[float] = None
    gpu_memory_used_mb: Optional[int] = None
    gpu_memory_total_mb: Optional[int] = None
    disk_free_gb: float
    uptime_seconds: int
    websocket_clients: int
    timestamp: datetime


class HealthResponse(BaseModel):
    status: Literal["healthy", "degraded", "down"]
    db: Literal["connected", "disconnected"]
    camera_monitor: Literal["running", "stopped", "disabled"]
    timestamp: datetime


class PingResponse(BaseModel):
    status: Literal["ok", "degraded"]
    db: Literal["connected", "disconnected"]
    timestamp: datetime


class RootResponse(BaseModel):
    name: str
    version: str
    status: str
    environment: str
    docs_url: str
    timestamp: datetime


# ------------------------------------------------------------------ WebSocket payloads

class WSDetection(BaseModel):
    model_config = ConfigDict(extra="ignore")

    track_id: int = Field(ge=0)
    object_class: str = Field(min_length=1, max_length=20)
    confidence: Optional[float] = Field(default=None, ge=0, le=1)
    cx: Optional[int] = Field(default=None, ge=0)
    cy: Optional[int] = Field(default=None, ge=0)
    bbox_x1: Optional[int] = Field(default=None, ge=0)
    bbox_y1: Optional[int] = Field(default=None, ge=0)
    bbox_x2: Optional[int] = Field(default=None, ge=0)
    bbox_y2: Optional[int] = Field(default=None, ge=0)
    in_fence: bool = False
    zone_name: Optional[str] = Field(default=None, max_length=100)
    zone_type: Optional[ZoneType] = None
    loitering: bool = False
    time_in_zone_seconds: int = Field(default=0, ge=0)
    direction: Direction = Direction.STATIONARY
    risk_score: RiskScore = 0
    risk_level: RiskLevel = RiskLevel.NORMAL
    person_uuid: Optional[str] = Field(default=None, max_length=64)
    #: Set when this person is holding a weapon (weapon model or COCO knife/bat), for the console's weapon count.
    weapon_class: Optional[str] = Field(default=None, max_length=20)
    weapon_confidence: Optional[float] = Field(default=None, ge=0, le=1)


class WSAlert(BaseModel):
    model_config = ConfigDict(extra="ignore")

    alert_id: Optional[str] = Field(default=None, pattern=ALERT_ID_PATTERN)
    alert_type: AlertType
    risk_score: RiskScore
    risk_level: Optional[RiskLevel] = None
    risk_reasons: List[str] = Field(default_factory=list)
    snapshot_path: Optional[str] = None
    track_id: Optional[int] = Field(default=None, ge=0)
    person_uuid: Optional[str] = Field(default=None, max_length=64)
    zone_name: Optional[str] = Field(default=None, max_length=100)
    zone_type: Optional[ZoneType] = None


class WSStats(BaseModel):
    model_config = ConfigDict(extra="ignore")

    people_count: int = Field(default=0, ge=0)
    vehicle_count: int = Field(default=0, ge=0)
    animal_count: int = Field(default=0, ge=0)
    active_alerts: int = Field(default=0, ge=0)
    fps: float = Field(default=0.0, ge=0, le=1000)


class WSFrameData(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: Literal["frame_data"]
    camera_id: Optional[str] = None
    frame: Optional[str] = None
    detections: List[WSDetection] = Field(default_factory=list, max_length=500)
    alerts: List[WSAlert] = Field(default_factory=list, max_length=50)
    stats: WSStats = Field(default_factory=WSStats)
    timestamp: Optional[datetime] = None

    @field_validator("frame")
    @classmethod
    def _strip_data_uri(cls, value: Optional[str]) -> Optional[str]:
        if value and value.startswith("data:"):
            return value.split(",", 1)[-1]
        return value


class WSAcknowledge(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: Literal["acknowledge"]
    alert_id: str = Field(pattern=ALERT_ID_PATTERN)
    false_alarm: bool = False
    notes: Optional[str] = Field(default=None, max_length=5000)


# ------------------------------------------------------------------ video analysis

class HighRiskMoment(BaseModel):
    start_seconds: float
    end_seconds: float
    peak_risk: int


class AnalysisSummary(BaseModel):
    persons_found: int
    vehicles_found: int
    animals_found: int
    #: weapon type -> number of distinct people seen carrying it
    weapons_found: Dict[str, int] = Field(default_factory=dict)
    #: weapon type -> processed frames it was seen in
    weapon_sightings: Dict[str, int] = Field(default_factory=dict)
    alerts_detected: int
    alerts_created: int
    evidence_saved: int
    high_risk_moments: List[HighRiskMoment] = Field(default_factory=list)
    duration_seconds: Optional[float] = None
    frames_read: Optional[int] = None
    frames_processed: Optional[int] = None
    fps: Optional[float] = None
    resolution: Optional[List[int]] = None
    zones_used: Optional[int] = None


class AnalysisJobResponse(BaseModel):
    job_id: str
    evidence_id: Optional[int] = None
    camera_id: Optional[str] = None
    standalone: bool
    status: Literal["queued", "loading", "running", "complete", "failed"]
    percent: float
    frames_read: int
    frames_total: int
    persons: int
    vehicles: int
    animals: int
    #: people seen carrying a weapon so far
    weapons: int = 0
    alerts: int
    video_seconds: float
    created_at: datetime
    finished_at: Optional[datetime] = None
    error: Optional[str] = None
    summary: Optional[AnalysisSummary] = None
    alerts_created: List[str] = Field(default_factory=list)
    evidence_created: List[int] = Field(default_factory=list)
